apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-worker
  labels:
    app: object-detection-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: object-detection-worker
  template:
    metadata:
      labels:
        app: object-detection-worker
    spec:
      containers:
      - name: object-detection-worker
        image: GOOGLE_CLOUD_IMAGE
        env:
        - name: GCP_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: gcp-project-id
        - name: PUBSUB_SUBSCRIPTION
          value: "detection-workers"
        - name: PUBSUB_RESULTS_TOPIC
          value: "detection-results"
        - name: GCS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: gcs-bucket
        - name: API_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api-service-url
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      terminationGracePeriodSeconds: 60
      serviceAccountName: object-detection-worker-sa