apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-worker
  labels:
    app: object-detection-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detection-worker
  template:
    metadata:
      labels:
        app: object-detection-worker
    spec:
      containers:
      - name: object-detection-worker
        image: GOOGLE_CLOUD_IMAGE
        ports:
        - containerPort: 8000
        env:
        - name: GCP_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: gcp-project-id
        - name: PUBSUB_TOPIC
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: pubsub-topic
        - name: GCS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: gcs-bucket
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 18
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      serviceAccountName: object-detection-worker-sa