apiVersion: v1
kind: ServiceAccount
metadata:
  name: object-detection-sa
  namespace: object-detection
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ObjectDetectionRole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: object-detection
  name: object-detection-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: object-detection-rolebinding
  namespace: object-detection
subjects:
- kind: ServiceAccount
  name: object-detection-sa
  namespace: object-detection
roleRef:
  kind: Role
  name: object-detection-role
  apiGroup: rbac.authorization.k8s.io