# Create this secret manually or via kubectl:
# kubectl create secret generic app-secrets \
#   --from-literal=callback-api-url="http://object-detection-api:8000"

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  callback-api-url: "http://object-detection-api:8000"