apiVersion: v1
kind: ServiceAccount
metadata:
  name: object-detection-worker-sa
  annotations:
    iam.gke.io/gcp-service-account: github-actions-deployer@processing-469712.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: object-detection-worker-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: object-detection-worker-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: object-detection-worker-role
subjects:
- kind: ServiceAccount
  name: object-detection-worker-sa
  namespace: default