apiVersion: v1
kind: Service
metadata:
  name: object-detection-worker-service
  namespace: object-detection
  labels:
    app: object-detection-worker
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: object-detection-worker