apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-worker
  namespace: object-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: object-detection-worker
  template:
    metadata:
      labels:
        app: object-detection-worker
    spec:
      serviceAccountName: object-detection-sa
      containers:
      - name: worker
        image: object-detection-worker:latest
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: S3_BUCKET
          value: "object-detection-images"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: METADATA_DB_HOST
          value: "redis"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: model-cache
          mountPath: /root/.cache
      volumes:
      - name: model-cache
        emptyDir: {}